name: cygwin-action-workflow
on:
  push:
    # # Sequence of patterns matched against refs/tags
    # tags:
    #   - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    #   - 'c*'
      
permissions:
    contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: mingw32, env: i686 }
          - { sys: ucrt64,  env: ucrt-x86_64 }
          - { sys: clang64, env: clang-x86_64 }
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            curl
            git     
            mingw-w64-${{matrix.env}}-openssl
            mingw-w64-${{matrix.env}}-gcc
            
            
      # - run: |
      #     echo $(pwd) && \
      #     ls && \
      #     cd '${{ github.workspace }}' && \
      #     ls && \
      #     g++ --version
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "C:/tools/cygwin"
          filename: "cygwin-${{ github.ref_name }}-${{ matrix.sys }}.zip"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "C:/tools/cygwin/cygwin-${{ github.ref_name }}-${{ matrix.sys }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
